### PR TITLE
Update URLs that now redirect

### PR DESCRIPTION
**Pull request by flbn**
There are several links to the previous url where the Swift book was published, this PR here just gets rid of the main offender in the README. i'm hesitant to touch the other links, so i'll just drop this search for posterity: https://github.com/search?q=repo%3Aapple%2Fswift-book%20https%3A%2F%2Fdocs.swift.org%2Fswift-book%2F&type=code

as per https://github.com/apple/swift-book/issues/72

### CODE REVIEW

**Comment by flbn** [comment]
turns out that search revealed only one other link that wasn't updated in the `TSPL.docc/header-staging.html` file. grepping and gh search don't result in any other hits, so this should be all of them?

**Comment by amartini51** [comment]
Thanks! Do you mind if I revise the commit messages to be a little more informative and force-push to your branch?

**Comment by flbn** [comment]
not a problem!

**Comment by amartini51** [comment]
@flbn Ok if I merge now, using the rewritten commit 63d118e7?

**Review by amartini51 — APPROVED** [review]

**Comment by flbn** [comment]
yup👌🏽

**Pull request merged**
