### PR TITLE
Spelling & spacing modify

### PR DESCRIPTION
**Pull request by bbiguduk**
Hi!
I'm reading this swift book and requesting PR because there are something wrong.

1. Spelling error
This mention is about actor not structure, so I modified spelling from structure type to actor type.

2. Spacing error
There are incorrect punctuation in that sentence.

### CODE REVIEW

**Comment by amartini51** [comment]
Thanks for catching these issues!

Looking at the [RST version](https://github.com/apple/swift-book/blame/c0150988c363ea1820515b49faba0d45ecee9a55/ReferenceManual/Declarations.rst#L3140) of the book, before converting to markdown, the places where you added a space should actually be a paragraph break.  It looks like the exporter didn't properly handle multi-paragraph list items, and we missed that issue during the page-turns.

**Comment by bbiguduk** [comment]
Thank you!
I understand your answer.

Yes! You push to my branch to match commit message and to add paragraph breaks.

Thank you again for detail information!

**Comment by bbiguduk** [comment]
> fore converting to markdown, the places where you added a space should actually be a paragraph break. It looks like the exporter didn't properly handle multi-paragraph list items, and we missed that issue during the page-turns.
> 
> Is it ok if I push to your branch now, to match commit message style, and to add paragraph breaks

Thank you!
I understand your answer.

Yes! You push to my branch to match commit message and to add paragraph breaks.

Thank you again for detail information!

**Comment by amartini51** [comment]
Thanks.  I changed the commit messages, so they explain the changes.

I also noticed the mistake "a actor" near the mistake you fixed ("a struct") and changed that.

I think these changes are ready for review now.

**Comment by amartini51** [comment]
@bbiguduk Do my new commits look ok to you? I'm ready to merge this, but you still have this PR marked as "draft".

**Comment by bbiguduk** [comment]
> @bbiguduk Do my new commits look ok to you? I'm ready to merge this, but you still have this PR marked as "draft".

@amartini51 I'm sorry, for this status. I changed to ready to review.

**Comment by amartini51** [comment]
@bbiguduk Thank you! I merged this fix into 'main'. You can delete your local branch now.

**Comment by bbiguduk** [comment]
> @bbiguduk Thank you! I merged this fix into 'main'. You can delete your local branch now.

Thank you! 👍

**Pull request merged**
