### PR TITLE
Remove redundant sentence

### PR DESCRIPTION
**Pull request by SimplyDanny**
Seems like the message of the previous sentence is pretty much the same.

### CODE REVIEW

**Review by amartini51 — CHANGES_REQUESTED** [review]
I don't think this is redundant — but it looks like it's unclear:

- If there are multiple extensions in the same file, and those extensions all extend the same type, then all of those extensions have the same access control level.  This file might not be the same as where the extended type is defined.
- If the extensions are in the same file as the type they extend, the extensions have the same access control as the type they extend.

If you'd like to try rewriting for clarity, please go ahead on this PR.  Otherwise, you can let me know and I'll try rewriting.

**Comment by SimplyDanny** [comment]
> If you'd like to try rewriting for clarity, please go ahead on this PR. Otherwise, you can let me know and I'll try rewriting.

I tried to reword the paragraph.

**Comment by amartini51** [comment]
Thanks @SimplyDanny — I think we're going to come back to this.  The rewrite has several issues, and I'm currently focusing on new content for topics like safe concurrency and noncopyable types.  I set a reminder to look at this again in June, when hopefully more time will be available.

**Comment by amartini51** [comment]
Closing this PR in favor of the rewrite on https://github.com/apple/swift-book/pull/315

Thanks for pointing out the hard to read wording!

**Pull request closed without merging**
