### PR TITLE
Mark "syntax outline" code listings as Swift

### PR DESCRIPTION
**Pull request by Kyle-Ye**
- Update code snippet to Swift
Fix some Swift code snippet does not use `swift` metadata

> Actually there are other cases for this situation. Since they are incomplete Swift Code, should we mark the `swift` metadata to add syntax highlighting support?

Before (Without Swift Syntax highlighting)
image

After
image

- Update gitignore
Ignore the .docc-build folder after `docc preview TSPL.docc`

### CODE REVIEW

**Comment by krilnon** [comment]
Ideally these would render with a presentation similar to the screenshot in #4, rather than as normal Swift code.

**Comment by Kyle-Ye** [comment]
> Ideally these would render with a presentation similar to the screenshot in #4, rather than as normal Swift code.

+1. Maybe we need add such feature in Swift-DocC & Swift-DocC-Render.

**Comment by amartini51** [comment]
@swift-ci Please test.

**Comment by Kyle-Ye** [comment]
> > Ideally these would render with a presentation similar to the screenshot in #4, rather than as normal Swift code.
> 
> +1. Maybe we need add such feature in Swift-DocC & Swift-DocC-Render.

IMO we need to introduce a new structure to capture this in Swift Markdown. What's your opinion on this? cc @QuietMisdreavus 

And then emit it from Swift-DocC to Swift-DocC-Render/Xcode.

The Swift-DocC-Render's implementation detail could follow the current behavior of swift-book website. (Xcode's documentation support should be implemented in Apple and is not the scope of the open source topic cc @franklinsch )

image

**Comment by QuietMisdreavus** [comment]
> > > Ideally these would render with a presentation similar to the screenshot in #4, rather than as normal Swift code.
> > 
> > 
> > +1. Maybe we need add such feature in Swift-DocC & Swift-DocC-Render.
> 
> IMO we need to introduce a new structure to capture this in Swift Markdown. What's your opinion on this? cc @QuietMisdreavus

Swift-Markdown would be the right place for this, however IIRC it would be a breaking change. As a data structure, code blocks currently store their contents as plain text, not as a collection of inner structures. I do think it would be a good addition, so we should file the issue(s) and get that working.

**Comment by amartini51** [comment]
I think this is an improvement over no syntax highlighting.  However, for the sake of consistency, we should either change all of the syntax outlines in the reference, or leave them all as-is.  The fact that they don't have a language marked was probably an oversight in the RST-to-markdown export process.  @Kyle-Ye ok if I push more commits to this branch?  I don't want to conflict with work you might still be doing.

> Ideally these would render with a presentation similar to the screenshot in #4, rather than as normal Swift code.

The tools and content changes to render `<# #>` as placeholder tokens can happen on its own PR.

**Comment by Kyle-Ye** [comment]
> I think this is an improvement over no syntax highlighting. However, for the sake of consistency, we should either change all of the syntax outlines in the reference, or leave them all as-is. The fact that they don't have a language marked was probably an oversight in the RST-to-markdown export process. @Kyle-Ye ok if I push more commits to this branch? I don't want to conflict with work you might still be doing.
> 
> > Ideally these would render with a presentation similar to the screenshot in #4, rather than as normal Swift code.
> 
> The tools and content changes to render `<# #>` as placeholder tokens can happen on its own PR.

Yes, you are free to push more commits on this branch.

**Comment by amartini51** [comment]
Thanks, @Kyle-Ye.  I think I've got the rest of them in commit 45717bf1.

**Comment by amartini51** [comment]
@swift-ci Please build.

**Review by amartini51 — APPROVED** [review]

**Review by krilnon — APPROVED** [review]

**Pull request merged**
